package corba.exchange_domain.iExchangePackage;


/**
* exchange_domain/iExchangePackage/customer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from stockexchange/exchange.idl
* Wednesday, July 1, 2015 11:19:20 PM EDT
*/

public final class customer implements org.omg.CORBA.portable.IDLEntity
{
  public String name = null;
  public String street1 = null;
  public String street2 = null;
  public String city = null;
  public String province = null;
  public String postalCode = null;
  public String country = null;

  public customer ()
  {
  } // ctor

  public customer (String _name, String _street1, String _street2, String _city, String _province, String _postalCode, String _country)
  {
    name = _name;
    street1 = _street1;
    street2 = _street2;
    city = _city;
    province = _province;
    postalCode = _postalCode;
    country = _country;
  } // ctor

} // class customer
