package corba.exchange_domain.iExchangePackage;


/**
* exchange_domain/iExchangePackage/lstCorShareItemHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from stockexchange/exchange.idl
* Wednesday, July 1, 2015 11:19:20 PM EDT
*/

public final class lstCorShareItemHolder implements org.omg.CORBA.portable.Streamable
{
  public corba.exchange_domain.iExchangePackage.corShareItem value[] = null;

  public lstCorShareItemHolder ()
  {
  }

  public lstCorShareItemHolder (corba.exchange_domain.iExchangePackage.corShareItem[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = corba.exchange_domain.iExchangePackage.lstCorShareItemHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    corba.exchange_domain.iExchangePackage.lstCorShareItemHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return corba.exchange_domain.iExchangePackage.lstCorShareItemHelper.type ();
  }

}
