
package WebServices.ExchangeClientServices;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ExchangeWSImplService", targetNamespace = "http://exchange.stockexchange/", wsdlLocation = "http://localhost:8888/WS/TSX?wsdl")
public class ExchangeWSImplService
    extends Service
{

    private final static URL EXCHANGEWSIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException EXCHANGEWSIMPLSERVICE_EXCEPTION;
    private final static QName EXCHANGEWSIMPLSERVICE_QNAME = new QName("http://exchange.stockexchange/", "ExchangeWSImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8888/WS/TSX?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        EXCHANGEWSIMPLSERVICE_WSDL_LOCATION = url;
        EXCHANGEWSIMPLSERVICE_EXCEPTION = e;
    }

    public ExchangeWSImplService() {
        super(__getWsdlLocation(), EXCHANGEWSIMPLSERVICE_QNAME);
    }

    public ExchangeWSImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), EXCHANGEWSIMPLSERVICE_QNAME, features);
    }

    public ExchangeWSImplService(URL wsdlLocation) {
        super(wsdlLocation, EXCHANGEWSIMPLSERVICE_QNAME);
    }

    public ExchangeWSImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, EXCHANGEWSIMPLSERVICE_QNAME, features);
    }

    public ExchangeWSImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ExchangeWSImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IExchange
     */
    @WebEndpoint(name = "ExchangeWSImplPort")
    public IExchange getExchangeWSImplPort() {
        return super.getPort(new QName("http://exchange.stockexchange/", "ExchangeWSImplPort"), IExchange.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IExchange
     */
    @WebEndpoint(name = "ExchangeWSImplPort")
    public IExchange getExchangeWSImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://exchange.stockexchange/", "ExchangeWSImplPort"), IExchange.class, features);
    }

    private static URL __getWsdlLocation() {
        if (EXCHANGEWSIMPLSERVICE_EXCEPTION!= null) {
            throw EXCHANGEWSIMPLSERVICE_EXCEPTION;
        }
        return EXCHANGEWSIMPLSERVICE_WSDL_LOCATION;
    }

}
