package exchange_domain;


/**
* exchange_domain/iExchangeOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from stockexchange/exchange.idl
* Monday, June 29, 2015 7:42:52 PM EDT
*/

public interface iExchangeOperations 
{

  // update share price
  boolean updateSharePrice (String symbol, float PRICE);
} // interface iExchangeOperations
