package exchange_domain;


/**
* exchange_domain/iExchangeOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from stockexchange/exchange.idl
* Tuesday, June 30, 2015 8:08:10 PM EDT
*/

public interface iExchangeOperations 
{

  // update share price
  boolean updateSharePrice (String symbol, float price);
  boolean registerBusiness (String symbol, float price);
  boolean unregister (String symbol);
} // interface iExchangeOperations
