package exchange_domain;


/**
* exchange_domain/iExchange.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from stockexchange/exchange.idl
* Monday, June 29, 2015 7:42:52 PM EDT
*/

public interface iExchange extends iExchangeOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface iExchange
