package exchange_domain;


/**
* exchange_domain/iExchange.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from stockexchange/exchange.idl
* Tuesday, June 30, 2015 8:08:10 PM EDT
*/

public interface iExchange extends iExchangeOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface iExchange
