package exchange_domain;


/**
* exchange_domain/iExchangeOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from stockexchange/exchange.idl
* Monday, June 29, 2015 9:38:30 PM EDT
*/

public interface iExchangeOperations 
{

  // update share price
  boolean updateSharePrice (String symbol, float price);
  boolean registerBusiness (String symbol, float price);
} // interface iExchangeOperations
