package exchange_domain;

/**
* exchange_domain/iExchangeHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from stockexchange/exchange.idl
* Tuesday, June 30, 2015 8:08:10 PM EDT
*/

public final class iExchangeHolder implements org.omg.CORBA.portable.Streamable
{
  public exchange_domain.iExchange value = null;

  public iExchangeHolder ()
  {
  }

  public iExchangeHolder (exchange_domain.iExchange initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = exchange_domain.iExchangeHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    exchange_domain.iExchangeHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return exchange_domain.iExchangeHelper.type ();
  }

}
