package corba.business_domain;


/**
* business_domain/interface_businessHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from business/business.idl
* Monday, June 29, 2015 7:52:39 PM EDT
*/

abstract public class interface_businessHelper
{
  private static String  _id = "IDL:business_domain/interface_business:1.0";

  public static void insert (org.omg.CORBA.Any a, interface_business that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static interface_business extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (interface_businessHelper.id(), "interface_business");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static interface_business read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_interface_businessStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, interface_business value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static interface_business narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof interface_business)
      return (interface_business)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      _interface_businessStub stub = new _interface_businessStub();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static interface_business unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof interface_business)
      return (interface_business)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      _interface_businessStub stub = new _interface_businessStub();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
