package corba.business_domain;


/**
* business_domain/interface_business.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from business/business.idl
* Monday, June 29, 2015 7:52:39 PM EDT
*/

public interface interface_business extends interface_businessOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface interface_business
