package business_domain;


/**
* business_domain/interface_businessPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from business/business.idl
* Monday, June 29, 2015 7:52:38 PM EDT
*/

public abstract class interface_businessPOA extends org.omg.PortableServer.Servant
 implements business_domain.interface_businessOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("getTicker", new java.lang.Integer (0));
    _methods.put ("issueShares", new java.lang.Integer (1));
    _methods.put ("recievePayment", new java.lang.Integer (2));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // business_domain/interface_business/getTicker
       {
         String $result = null;
         $result = this.getTicker ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // business_domain/interface_business/issueShares
       {
         String orderNum = in.read_string ();
         String brokerRef = in.read_string ();
         String businessSymbol = in.read_string ();
         int shareType = in.read_long ();
         float unitPrice = in.read_float ();
         int quantity = in.read_long ();
         float unitPriceOrder = in.read_float ();
         boolean $result = false;
         $result = this.issueShares (orderNum, brokerRef, businessSymbol, shareType, unitPrice, quantity, unitPriceOrder);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 2:  // business_domain/interface_business/recievePayment
       {
         String orderNum = in.read_string ();
         float totalPrice = in.read_float ();
         boolean $result = false;
         $result = this.recievePayment (orderNum, totalPrice);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:business_domain/interface_business:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public interface_business _this() 
  {
    return interface_businessHelper.narrow(
    super._this_object());
  }

  public interface_business _this(org.omg.CORBA.ORB orb) 
  {
    return interface_businessHelper.narrow(
    super._this_object(orb));
  }


} // class interface_businessPOA
