package business_domain;


/**
* business_domain/interface_businessOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from business/business.idl
* Monday, June 29, 2015 7:52:39 PM EDT
*/

public interface interface_businessOperations 
{
  String getTicker ();
  boolean issueShares (String orderNum, String brokerRef, String businessSymbol, int shareType, float unitPrice, int quantity, float unitPriceOrder);
  boolean recievePayment (String orderNum, float totalPrice);
} // interface interface_businessOperations
