package business_domain;

/**
* business_domain/interface_businessHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from business/business.idl
* Monday, June 29, 2015 7:52:39 PM EDT
*/

public final class interface_businessHolder implements org.omg.CORBA.portable.Streamable
{
  public business_domain.interface_business value = null;

  public interface_businessHolder ()
  {
  }

  public interface_businessHolder (business_domain.interface_business initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = business_domain.interface_businessHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    business_domain.interface_businessHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return business_domain.interface_businessHelper.type ();
  }

}
