module exchange_domain
{
    interface iExchange
    {
        // update share price
        boolean updateSharePrice(in string symbol, in float price);
        boolean registerBusiness(in string symbol, in float price);
        boolean unregister(in string symbol);

    };
};