package exchange_domain.iExchangePackage;

/**
* exchange_domain/iExchangePackage/corShareItemHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from stockexchange/exchange.idl
* Wednesday, July 1, 2015 11:19:20 PM EDT
*/

public final class corShareItemHolder implements org.omg.CORBA.portable.Streamable
{
  public exchange_domain.iExchangePackage.corShareItem value = null;

  public corShareItemHolder ()
  {
  }

  public corShareItemHolder (exchange_domain.iExchangePackage.corShareItem initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = exchange_domain.iExchangePackage.corShareItemHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    exchange_domain.iExchangePackage.corShareItemHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return exchange_domain.iExchangePackage.corShareItemHelper.type ();
  }

}
