package exchange_domain.iExchangePackage;


/**
* exchange_domain/iExchangePackage/corShareItem.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from stockexchange/exchange.idl
* Wednesday, July 1, 2015 11:19:20 PM EDT
*/

public final class corShareItem implements org.omg.CORBA.portable.IDLEntity
{
  public String orderNumString = null;
  public String businessSymbol = null;
  public int shareType = (int)0;
  public float unitPrice = (float)0;
  public int quantity = (int)0;

  public corShareItem ()
  {
  } // ctor

  public corShareItem (String _orderNumString, String _businessSymbol, int _shareType, float _unitPrice, int _quantity)
  {
    orderNumString = _orderNumString;
    businessSymbol = _businessSymbol;
    shareType = _shareType;
    unitPrice = _unitPrice;
    quantity = _quantity;
  } // ctor

} // class corShareItem
