
package business.WSClient;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "BusinessWSImplService", targetNamespace = "http://business/", wsdlLocation = "http://localhost:18001/WS/AAPL?wsdl")
public class BusinessWSImplService
    extends Service
{

    private final static URL BUSINESSWSIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException BUSINESSWSIMPLSERVICE_EXCEPTION;
    private final static QName BUSINESSWSIMPLSERVICE_QNAME = new QName("http://business/", "BusinessWSImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:18001/WS/AAPL?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BUSINESSWSIMPLSERVICE_WSDL_LOCATION = url;
        BUSINESSWSIMPLSERVICE_EXCEPTION = e;
    }

    public BusinessWSImplService() {
        super(__getWsdlLocation(), BUSINESSWSIMPLSERVICE_QNAME);
    }

    public BusinessWSImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), BUSINESSWSIMPLSERVICE_QNAME, features);
    }

    public BusinessWSImplService(URL wsdlLocation) {
        super(wsdlLocation, BUSINESSWSIMPLSERVICE_QNAME);
    }

    public BusinessWSImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BUSINESSWSIMPLSERVICE_QNAME, features);
    }

    public BusinessWSImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BusinessWSImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IBusiness
     */
    @WebEndpoint(name = "BusinessWSImplPort")
    public IBusiness getBusinessWSImplPort() {
        return super.getPort(new QName("http://business/", "BusinessWSImplPort"), IBusiness.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IBusiness
     */
    @WebEndpoint(name = "BusinessWSImplPort")
    public IBusiness getBusinessWSImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://business/", "BusinessWSImplPort"), IBusiness.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BUSINESSWSIMPLSERVICE_EXCEPTION!= null) {
            throw BUSINESSWSIMPLSERVICE_EXCEPTION;
        }
        return BUSINESSWSIMPLSERVICE_WSDL_LOCATION;
    }

}
