
package business.WSClient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IBusiness", targetNamespace = "http://business/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IBusiness {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTicker", targetNamespace = "http://business/", className = "business.GetTicker")
    @ResponseWrapper(localName = "getTickerResponse", targetNamespace = "http://business/", className = "business.GetTickerResponse")
    @Action(input = "http://business/IBusiness/getTickerRequest", output = "http://business/IBusiness/getTickerResponse")
    public String getTicker();

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "issueShares", targetNamespace = "http://business/", className = "business.IssueShares")
    @ResponseWrapper(localName = "issueSharesResponse", targetNamespace = "http://business/", className = "business.IssueSharesResponse")
    @Action(input = "http://business/IBusiness/issueSharesRequest", output = "http://business/IBusiness/issueSharesResponse")
    public boolean issueShares(
        @WebParam(name = "arg0", targetNamespace = "")
        ShareOrder arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "recievePayment", targetNamespace = "http://business/", className = "business.RecievePayment")
    @ResponseWrapper(localName = "recievePaymentResponse", targetNamespace = "http://business/", className = "business.RecievePaymentResponse")
    @Action(input = "http://business/IBusiness/recievePaymentRequest", output = "http://business/IBusiness/recievePaymentResponse")
    public boolean recievePayment(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        float arg1);

}
