package corba.exchange_domain;

/**
* exchange_domain/iExchangeHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from stockexchange/exchange.idl
* Wednesday, July 1, 2015 11:19:19 PM EDT
*/

public final class iExchangeHolder implements org.omg.CORBA.portable.Streamable
{
  public iExchange value = null;

  public iExchangeHolder ()
  {
  }

  public iExchangeHolder (iExchange initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = iExchangeHelper.read(i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    iExchangeHelper.write(o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return iExchangeHelper.type();
  }

}
