package corba.exchange_domain;


/**
* exchange_domain/iExchangeOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from stockexchange/exchange.idl
* Wednesday, July 1, 2015 11:19:19 PM EDT
*/

public interface iExchangeOperations 
{

  // update share price
  boolean updateSharePrice (String symbol, float price);
  boolean registerBusiness (String symbol, float price);
  boolean unregister (String symbol);
  void clientOrder (corba.exchange_domain.iExchangePackage.corShareItem[] corShares, corba.exchange_domain.iExchangePackage.customer corCustomer);
} // interface iExchangeOperations
