package corba.exchange_domain;


/**
* exchange_domain/iExchangeHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from stockexchange/exchange.idl
* Wednesday, July 1, 2015 11:19:19 PM EDT
*/

abstract public class iExchangeHelper
{
  private static String  _id = "IDL:exchange_domain/iExchange:1.0";

  public static void insert (org.omg.CORBA.Any a, iExchange that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static iExchange extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (iExchangeHelper.id(), "iExchange");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static iExchange read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_iExchangeStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, iExchange value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static iExchange narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof iExchange)
      return (iExchange)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      _iExchangeStub stub = new _iExchangeStub();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static iExchange unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof iExchange)
      return (iExchange)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      _iExchangeStub stub = new _iExchangeStub();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
