package corba.broker_domain;


/**
* broker_domain/_iBrokerStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from stockexchange/broker.idl
* Thursday, July 2, 2015 5:52:00 PM EDT
*/

public class _iBrokerStub extends org.omg.CORBA.portable.ObjectImpl implements iBroker
{

  public boolean sellShares (String ticker, String shareType, int quantity, int custID)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("sellShares", true);
                $out.write_string (ticker);
                $out.write_string (shareType);
                $out.write_long (quantity);
                $out.write_long (custID);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return sellShares (ticker, shareType, quantity, custID        );
            } finally {
                _releaseReply ($in);
            }
  } // sellShares

  public int registerCustomer (String name, String street, String city, String province, String postalCode, String country)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("registerCustomer", true);
                $out.write_string (name);
                $out.write_string (street);
                $out.write_string (city);
                $out.write_string (province);
                $out.write_string (postalCode);
                $out.write_string (country);
                $in = _invoke ($out);
                int $result = $in.read_long ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return registerCustomer (name, street, city, province, postalCode, country        );
            } finally {
                _releaseReply ($in);
            }
  } // registerCustomer

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:broker_domain/iBroker:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _iBrokerStub
