package corba.broker_domain;


/**
* broker_domain/iBroker.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from stockexchange/broker.idl
* Thursday, July 2, 2015 5:52:00 PM EDT
*/

public interface iBroker extends iBrokerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface iBroker
