package corba.broker_domain;

/**
* broker_domain/iBrokerHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from stockexchange/broker.idl
* Thursday, July 2, 2015 5:52:00 PM EDT
*/

public final class iBrokerHolder implements org.omg.CORBA.portable.Streamable
{
  public iBroker value = null;

  public iBrokerHolder ()
  {
  }

  public iBrokerHolder (iBroker initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = iBrokerHelper.read(i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    iBrokerHelper.write(o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return iBrokerHelper.type();
  }

}
