package corba.broker_domain;


/**
* broker_domain/iBrokerHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from stockexchange/broker.idl
* Thursday, July 2, 2015 5:52:00 PM EDT
*/

abstract public class iBrokerHelper
{
  private static String  _id = "IDL:broker_domain/iBroker:1.0";

  public static void insert (org.omg.CORBA.Any a, iBroker that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static iBroker extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (iBrokerHelper.id(), "iBroker");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static iBroker read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_iBrokerStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, iBroker value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static iBroker narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof iBroker)
      return (iBroker)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      _iBrokerStub stub = new _iBrokerStub();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static iBroker unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof iBroker)
      return (iBroker)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      _iBrokerStub stub = new _iBrokerStub();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
