package corba.broker_domain;


/**
* broker_domain/iBrokerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from stockexchange/broker.idl
* Thursday, July 2, 2015 5:52:00 PM EDT
*/

public interface iBrokerOperations 
{
  boolean sellShares (String ticker, String shareType, int quantity, int custID);
  int registerCustomer (String name, String street, String city, String province, String postalCode, String country);
} // interface iBrokerOperations
